"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 10:11:19.187583
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)

    op.create_table('patient_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'version', name='uq_patient_version')
    )
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_profiles_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_profiles_patient_id'), ['patient_id'], unique=False)

    op.create_table('trials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('index_status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trials_owner_id'), ['owner_id'], unique=False)

    op.create_table('patient_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('observed_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_observations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_observations_profile_id'), ['profile_id'], unique=False)

    op.create_table('protocol_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trial_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('protocol_version', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=600), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('pages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_id', 'version', name='uq_protocol_trial_version')
    )
    with op.batch_alter_table('protocol_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_documents_trial_id'), ['trial_id'], unique=False)

    op.create_table('eligibility_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('trial_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('protocol_version', sa.String(length=80), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('patient_profile_id', sa.String(length=36), nullable=False),
    sa.Column('patient_profile_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('overall_status', sa.String(length=40), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['protocol_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_runs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eligibility_runs_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eligibility_runs_trial_id'), ['trial_id'], unique=False)

    op.create_table('protocol_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trial_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_rule', sa.JSON(), nullable=True),
    sa.Column('required_attributes', sa.JSON(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['protocol_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_criteria_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_criteria_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_criteria_trial_id'), ['trial_id'], unique=False)

    op.create_table('agent_execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('node', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['eligibility_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'node', name='uq_agent_log_run_node')
    )
    with op.batch_alter_table('agent_execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_execution_logs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_execution_logs_run_id'), ['run_id'], unique=False)

    op.create_table('contradiction_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('finding_type', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['eligibility_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contradiction_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contradiction_findings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contradiction_findings_run_id'), ['run_id'], unique=False)

    op.create_table('criterion_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comparison_method', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['eligibility_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criterion_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criterion_evaluations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_criterion_evaluations_run_id'), ['run_id'], unique=False)

    op.create_table('evidence_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=20), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['eligibility_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_references_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_references_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_references_run_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_references_owner_id'))

    op.drop_table('evidence_references')
    with op.batch_alter_table('criterion_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criterion_evaluations_run_id'))
        batch_op.drop_index(batch_op.f('ix_criterion_evaluations_owner_id'))

    op.drop_table('criterion_evaluations')
    with op.batch_alter_table('contradiction_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contradiction_findings_run_id'))
        batch_op.drop_index(batch_op.f('ix_contradiction_findings_owner_id'))

    op.drop_table('contradiction_findings')
    with op.batch_alter_table('agent_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_execution_logs_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_execution_logs_owner_id'))

    op.drop_table('agent_execution_logs')
    with op.batch_alter_table('protocol_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_criteria_trial_id'))
        batch_op.drop_index(batch_op.f('ix_protocol_criteria_owner_id'))
        batch_op.drop_index(batch_op.f('ix_protocol_criteria_document_id'))

    op.drop_table('protocol_criteria')
    with op.batch_alter_table('eligibility_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_runs_trial_id'))
        batch_op.drop_index(batch_op.f('ix_eligibility_runs_patient_id'))
        batch_op.drop_index(batch_op.f('ix_eligibility_runs_owner_id'))

    op.drop_table('eligibility_runs')
    with op.batch_alter_table('protocol_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_documents_trial_id'))
        batch_op.drop_index(batch_op.f('ix_protocol_documents_owner_id'))

    op.drop_table('protocol_documents')
    with op.batch_alter_table('patient_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_observations_profile_id'))
        batch_op.drop_index(batch_op.f('ix_patient_observations_owner_id'))

    op.drop_table('patient_observations')
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trials_owner_id'))

    op.drop_table('trials')
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_profiles_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_profiles_owner_id'))

    op.drop_table('patient_profiles')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_owner_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
